---
include:
  - project: shore/ci-templates
    file: templates/pre-commit.yml
  - project: shore/ci-templates
    file: templates/pre-commit-repo.yml
  - project: shore/ci-templates
    file: templates/docker.yml

stages:
  - test
  - build
  - deploy

docker-build:
  extends: .docker-build-shore
  tags: [ns4.shore.co.il]

docker-push:
  extends: .docker-push
  tags: [ns4.shore.co.il]
